load_defaults: 8.9.0
development:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://arcdex-solr:8983/solr/arclight" %>
test: &test
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://arcdex-solr:8983/solr/arclight-test" %>
production:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://arcdex-solr:8983/solr/arclight" %>
